version: "3.9"

services:
    db:
        image: mysql:8.0
        container_name: fakestore_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: fakestore
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fakestore_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - db
        ports:
            - "8000:8000"
        tty: true
        stdin_open: true

volumes:
    db_data:
