version: "3.8"

services:
    app:
        image: php:8.2-cli
        container_name: fakestore_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - db
        command: bash -c "composer install && php artisan key:generate && php artisan serve --host=0.0.0.0 --port=8000"

    db:
        image: mysql:8.0
        container_name: fakestore_db
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: fakestore
        ports:
            - "3307:3306" # Alterei para 3307 para evitar conflito
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
